// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpifpixfikjtmabadwmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwaWZwaXhmaWtqdG1hYmFkd215Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxOTE5NzIsImV4cCI6MjA2NDc2Nzk3Mn0.q0r32zB37SKNHJJnPbUEv2IqtvaAqTvgm4s9Qb_WTTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);